//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbsys.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENTS
    {
        public AGENTS()
        {
            this.CUSTOMER = new HashSet<CUSTOMER>();
            this.ORDERS = new HashSet<ORDERS>();
        }
    
        public string AGENT_CODE { get; set; }
        public string AGENT_NAME { get; set; }
        public string WORKING_AREA { get; set; }
        public Nullable<decimal> COMMISSION { get; set; }
        public string PHONE_NO { get; set; }
        public string COUNTRY { get; set; }
    
        public virtual ICollection<CUSTOMER> CUSTOMER { get; set; }
        public virtual ICollection<ORDERS> ORDERS { get; set; }
    }
}
